version: '3.8'

services:
  bookingsdb:
    image: mysql
    container_name: bookingsdb
    environment:
      MYSQL_ROOT_PASSWORD: bookings
      MYSQL_DATABASE: bookings
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h", "bookingsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - bookings-data:/var/lib/mysql
  paymentsdb:
    image: mysql
    container_name: paymentsdb
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: payments
      MYSQL_DATABASE: payments
    healthcheck:
      test: [ "CMD", "mysqladmin","ping","-h", "paymentsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - payments-data:/var/lib/mysql
  booking-service:
    image: booking-service
    container_name: booking-service
    build: ./Booking-Service
    environment:
      MYSQL_HOST: bookingsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: bookings
    depends_on:
      bookingsdb:
        condition: service_healthy
    ports:
      - '9090:9090'
  payment-service:
    image: payment-service
    container_name: payment-service
    build: ./payment-service
    environment:
      MYSQL_HOST: paymentsdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: payments
    depends_on:
      paymentsdb:
        condition: service_healthy
    ports:
      - '9091:9090'
volumes:
  bookings-data:
  payments-data:
