version: '3.8'

services:
  bookingsdb:
    image: mysql
    container_name: bookingsdb
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h", "bookingsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: bookings
      MYSQL_DATABASE: bookings
  paymentsdb:
    image: mysql
    container_name: paymentsdb
    healthcheck:
      test: [ "CMD", "mysqladmin","ping","-h", "paymentsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: payments
      MYSQL_DATABASE: payments
  booking-service:
    image: booking-service
    container_name: booking-service
    build: ./Booking-Service
    depends_on:
      bookingsdb:
        condition: service_healthy
    ports:
      - '9090:9090'
  payment-service:
    image: payment-service
    container_name: payment-service
    build: ./Booking-Service
    depends_on:
      paymentsdb:
        condition: service_healthy
    ports:
      - '9090:9090'