server:
  port: 8080
spring:
  application:
    name: Booking-Service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookings?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:roor}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
