server:
  port: ${SERVER_PORT:9091}
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:paymentsdb}:${MYSQL_PORT:3308}/${MYSQL_DB:payments}?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:payments}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
razorpay:
  keyId: rzp_test_SabbQfGhqf4Np4
  keySecret: pVA5ozafQrFBwHGQiSXdhWi7
