server:
  port: 9091
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/payments?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
razorpay:
  keyId: rzp_test_SabbQfGhqf4Np4
  keySecret: pVA5ozafQrFBwHGQiSXdhWi7
