server:
  port: 8080
spring:
  application:
    name: Booking-Service
  datasource:
    url: jdbc:mysql://localhost:3306/bookings?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Only if Eureka server is running locally
  instance:
    prefer-ip-address: true