server:
  port: 9091
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:9092"
#        - "localhost:29092"
#        - "localhost:39092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers:
        - "localhost:9092"
#        - "localhost:29092"
#        - "localhost:39092"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
razorpay:
  keyId: rzp_test_SabbQfGhqf4Np4
  keySecret: pVA5ozafQrFBwHGQiSXdhWi7
